.Dd May 7, 2012
.Dt libcnotify 3
.Os libcnotify
.Sh NAME
.Nm libcnotify.h
.Nd Library to support cross-platform C error functions
.Sh LIBRARY
.Lb libcnotify
.Sh SYNOPSIS
.In libcnotify.h
.Pp
Support functions
.Ft const char *
.Fn libcnotify_get_version "void"
.Pp
Stream functions
.Ft int
.Fn libcnotify_stream_set "FILE *stream, libcnotify_error_t **error"
.Ft int
.Fn libcnotify_stream_open "const char *filename, libcnotify_error_t **error"
.Ft int
.Fn libcnotify_stream_close "libcnotify_error_t **error"
.Pp
Verbose functions
.Ft void
.Fn libcnotify_verbose_set "int verbose"
.Pp
Print functions
.Ft int
.Fn libcnotify_printf "const char *format, ..."
.Ft int
.Fn libcnotify_print_data "const uint8_t *data, size_t data_size, uint8_t print_data_flags"
.Ft int
.Fn libcnotify_print_error_backtrace "libcnotify_error_t *error"
.Pp
.Sh DESCRIPTION
The
.Fn libcnotify_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or -1 on error, dependent on the return type. For the actual return values refer to libcnotify.h
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
http://code.google.com/p/libclibs/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2008-2012 Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libcnotify.h include file
